#!/usr/bin/env bash
# Based on https://github.com/ludeeus/integration_blueprint
set -e

cd "$(dirname "$0")/.."

echo "Running ruff check..."
ruff check custom_components/kkt_kolbe/

echo "Running ruff format check..."
ruff format custom_components/kkt_kolbe/ --check

echo "All checks passed."
